services:
  db:
    build: ./db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRESS_DB: ${DB_NAME}

  web:
    build: ./web
    restart: always
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
  
  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --protocol http2 --url http://web:8000
    depends_on:
      - web
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - web
    
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus